### ISSUE TITLE
Хотелось бы, чтобы можно было вносить свой вклад в проект.

### ISSUE THREAD

**Issue by Jerrody** [ZernovTechno/AR#2]
Очень интересный проект, который за дешево дает возможность получить прелести современных AR очков. Появилось желание внести свой вклад в проект, но, к сожалению, код закрытый, что расстраивает.

**Comment by ZernovTechno** [comment]
Проект весит очень много, и хаб не дал запушить сюда весь архив. Поэтому выложил на гугол: https://drive.google.com/file/d/1KS0ScGoc__9d2ibDo_Zi84gS_LNeW1Jx/view?usp=drive_link

**Comment by Jerrody** [comment]
> Проект весит очень много, и хаб не дал запушить сюда весь архив. Поэтому выложил на гугол: https://drive.google.com/file/d/1KS0ScGoc__9d2ibDo_Zi84gS_LNeW1Jx/view?usp=drive_link

Можно поинтересоваться, а какая ошибка была? Может быть, я могу с этим помочь.

**Comment by Jerrody** [comment]
> Проект весит очень много, и хаб не дал запушить сюда весь архив. Поэтому выложил на гугол: https://drive.google.com/file/d/1KS0ScGoc__9d2ibDo_Zi84gS_LNeW1Jx/view?usp=drive_link

Кстати, есть идея, чтобы просто порционно пушить весь контент, не пробовали?

**Comment by MangriMen** [comment]
> Проект весит очень много, и хаб не дал запушить сюда весь архив. Поэтому выложил на гугол: https://drive.google.com/file/d/1KS0ScGoc__9d2ibDo_Zi84gS_LNeW1Jx/view?usp=drive_link

Настройте правильно git LFS для проекта и в теории на гитхаб будет литься только код, а все ассеты подтягиваться через LFS. Также в целом светую посмотреть про настройку репозитория для юнити проектов, там много что можно сделать чтобы гит лучше мерджил разницу и понимал какие файлы какого типа. Тоже не против был внести свой вклад в проект

**Comment by Jerrody** [comment]
> Сделано.

Раскумар.
